[build-system]
requires = ["setuptools", "wheel", "--extra-index-url https://download.pytorch.org/whl/cu113", "torch==1.10.2+cu113", "torchvision==0.11.3+cu113"]
build-backend = "setuptools.build_meta:__legacy__"